### ISSUE TITLE
Package cannot be installed on Windows - wrong URL

### ISSUE THREAD

**Issue by alesn** [adamgian/minify-selectors#54]
**Describe the bug**
The package cannot be installed on Windows because it is trying to download the release from a wrong URL on Github. 
Note in the 'Actual result' section below the requested URL is: 
https://github.com/adamgian/minify-selectors/releases/download/v2.6.0/minify-selectors-windows-64.exe.tar.gz

The file doesn't exist at that URL. The actual correct URL is (without the '.exe'):
https://github.com/adamgian/minify-selectors/releases/download/v2.6.0/minify-selectors-windows-64.tar.gz

**How to reproduce**
On Windows ...
npm install minify-selectors

**Expected result**
Package gets installed.

**Actual result**
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c node ./build/install.js
npm error Downloading release from https://github.com/adamgian/minify-selectors/releases/download/v2.6.0/minify-selectors-windows-64.exe.tar.gz
npm error Error fetching release: Request failed with status code 404

**Environment**
Windows 11 - x64

**Version**
2.6.0

**Comment by adamgian** [comment]
Thanks @alesn for your report, much appreciated.

Cannot believe I've missed this, will try to get a patch up soon.

**Comment by adamgian** [comment]
A new version ([2.6.2](https://www.npmjs.com/package/minify-selectors/v/2.6.2)) has been released to correct the URL.

Thanks so much for noticing and taking the time to report @alesn :)!

**Comment by alesn** [comment]
I can confirm that version 2.6.2 resolves this issue. Thank you for the fix!
